services:
  - type: web
    name: rls-gnn-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portals.server:app
    envVars:
      - key: PRODUCTION_MODE
        value: "true"
      - key: PYTHON_VERSION
        value: "3.10.12"
